#This file describes the key parameters of the reference experiment for testing (Table 1. in the article)

#WARNING: parameters should be in a list (even of size 1)

#Size of the state ($N_x$ in the article)
p: [36]

#Observation time sampling ($\Delta_t$ in the article) in MTU
dtObs: [0.05]

#Observation standard deviation ($\sigma^{\rm o}$ in the article)
std_o: [0.1]

#Fitering of the training set after DA (size of the window used for averaging in  number of time steps):
Nfil_train: [1]

#Time length of the simulation
T: [15.]

#Number of ensemble in the simulation
N: [20]

#seed for the random initialisation of the simulation
seed: [10]