#This file describes the key parameters of the reference experiment (Table 1. in the article)

#WARNING: parameters should be in a list (even of size 1)

params:
 #Size of the state ($N_x$ in the article)
 p: [36]

 #Observation time sampling ($\Delta_t$ in the article) in MTU
 dtObs: [0.05]

 #Observation standard deviation ($\sigma^{\rm o}$ in the article)
 std_o: [0.1]

 #Fitering of the training set after DA (size of the window used for averaging in  number of time steps):
 Nfil_train: [1]

#Name of the files
files:
# truth: 'simul-truth-N{N}-seed{seed}.npz'
 hybrid: 'simul-hybrid-p{p}-dtObs{dtObs}-std_o{std_o}-filter{Nfil_train}-N{N}-seed{seed}.npz'
# perfect: 'simul-perfect-dtObs{dtObs}-N{N}-seed{seed}.npz'
# trunc: 'simul-trunc-N{N}-seed{seed}.npz'