#This file describes the key parameters of the reference experiment for the training (Table 1. in the article)

#WARNING: parameters should be in a list (even of size 1)

#Size of the state ($N_x$ in the article)
p: [36]

#Observation time sampling ($\Delta_t$ in the article) in MTU
dtObs: [0.05]

#Observation standard deviation ($\sigma^{\rm o}$ in the article)
std_o: [0.1]

#Fitering of the training set after DA (size of the window used for averaging in  number of time steps):
Nfil_train: [1]

#Time length of the simulation
T: [15.]

#Number of ensemble in the simulation
N: [20]

#seed for the random initialisation of the simulation
seed: [10]

#THE FOLLOWING PARAMETERS ARE CONSTANT (NOT IN A LIST)
archi:
 - [43, 5, 'tanh']
 - [28, 1, 'tanh']

parnn:
 reg: 0.072 #L2 regularization term on the last layer
 batch_layer: 1 # Position of the batchlayer in the neural net (-1 for no batchlayer)

#Directory where to save the simualtions
savedir: 'simul/test'
weightsdir: 'weights'

#Template name of the files used in the experiments
template:
 #Initilisation file (generates by the true model)
 'initname': 'init-N{N}-seed{seed}.npy'

 #True simulation
 'truth': 'simul-truth-T{T}-N{N}-seed{seed}.npz'

 #Trunc simulation
 'trunc':  'simul-trunc-T{T}-N{N}-seed{seed}.npz'

 #Weights of the NN
 weights: 'weight-EnKFN-p{p}-dtObs{dtObs}-std_o{std_o}-filter{Nfil_train}.h5'

#Hybrid simulation
 hybrid: 'simul-hybrid-p{p}-dtObs{dtObs}-std_o{std_o}-filter{Nfil_train}-N{N}-seed{seed}.npz'