#This file describes the key parameters of the sensitivity experiment (Fig 2. of the article)

#WARNING: parameters should be in a list (even of size 1)

#Main parameters of the experiment
params: 
 #Size of the observation field ($N_y$ in the article)
 p: [18, 27, 36]

 #Observation time sampling ($\Delta_t$ in the article) in MTU
 dtObs: [0.01, 0.05, 0.1, 0.15]

 #Observation standard deviation ($\sigma^{\rm o}$ in the article)
 std_o: [0.05, 0.1, 0.2, 0.5, 1., 2.]

 #Fitering of the training set after DA (size of the window used for averaging in  number of time steps):
 Nfil_train: [1, 5]
 
 #Time length of the simulation
 T: [15]

#Name of the files
files:
 truth: 'simul-truth-T{T}-N{N}-seed{seed}.npz'
 hybrid: 'simul-hybrid-p{p}-dtObs{dtObs}-std_o{std_o}-filter{Nfil_train}-N{N}-seed{seed}.npz'
 trunc: 'simul-trunc-T{T}-N{N}-seed{seed}.npz'
 perfect: 'simul-perfect-dtObs{dtObs}-N{N}-seed{seed}.npz'